[deps]
ApplicationBuilder = "f9309374-59cc-5ff5-a120-e3e470a57b4a"
Atom = "c52e3926-4ff0-5f6e-af25-54175e0327b1"
CDDLib = "3391f64e-dcde-5f30-b752-e11513730f60"
CPLEX = "a076750e-1247-5638-91d2-ce28b192dca0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Dualization = "191a621a-6537-11e9-281d-650236a99e60"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Juno = "e5e0dc1b-0480-54bc-9374-aad01c23163d"
LanguageServer = "2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polyhedra = "67491407-f73d-577b-9b50-8179a7c68029"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
PrettyPrinting = "54e16d92-306c-5ea0-a30b-337be88ac337"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QHull = "a8468747-bd6f-53ef-9e5c-744dbc5c59e7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Redis = "4158d44a-2f00-5245-8bc1-1e26906f47fc"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
